name: George Burgin Photography
favicon: null
layout_spectrum: 0.5103585482574999
typography_spectrum: 0.7716358297038823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9857024934608489
  lightness: 0.6783628677949309
  saturation: 0.9468406406231225
  rhythmicContrast: 0.7668425762094557
purpose: []
